### PR TITLE
customized Download path with Options settings

### PR DESCRIPTION
**Pull request by nikiluk**
Hi! I've just added the option to customize the folder inside `~/Downloads/` where MDs and images are saved. Have a look.
2021-01-08 22 29 11 Extensions and 3 more pages -

By default the files are stored in `~/Downloads/MDClips/`, so that it's now easier to locate them and add to any MD vault later if needed.

2021-01-08 22 26 41 MDClips (1)

Linked to #41

### CODE REVIEW

**Comment by Offerel** [comment]
I'm new to this AddOn since today and really love it. Maybe I have set it up the wrong way, but I need to save images in a .dot folder underneath the markdown file. Thats why I have configured the path like the following `md/.media/{title}`. But in this case, the images are not saved. If i use `md/{title}`, a subfolder with markdown filename is created. Is there some way to store the images in such a hidden folder?

This would it make compatipel with my Roundcube AddOn: https://github.com/Offerel/roundcube_primitivenotes

**Comment by nikiluk** [comment]
@Offerel I'm not sure it will work with hidden .folders. Potentially, to make things work your way you can try using something like [SyncToy](https://www.minitool.com/backup-tips/synctoy-windows-10.html) and sync the contents of two folders. I understand that this is not perfect as this will require you to change source in all the .MD files too. Additional option could be creating a sync tool yourself using PowerShell or similar if you're on Mac or Linux. Sorry, if that doesn't sound very helpful.

**Comment by Offerel** [comment]
I understand the problem. I zry to use symlinked folders. Maybe this will solve the issue for me.

Later today, i will try today to make a parser on onPaste event in my notes plugin for Roundcube. Goal is it to automatically parse a Yaml header in prepared fields automatically. If that's finished, I try my luck with symlinked folders.

In both ways, i will report if that works.

BTW: i had the idea to build my own browser extension as companion for the Roundcube plugin like yours and searched for examples to grab selected text from a website. Now i found your extension and I fits perfectly in the workflow, except that it doesn't submit the result to the backend. But so, I can lay back and use your extension. Nice thing, many thanks.

**Comment by deathau** [comment]
I apologise, but I didn't see this PR until today, and I've been on a bit of a blitz so it looks like we have conflicts now.

Apart from that though, you _can_ already achieve this by specifying the folder in the title template, so I'm not sure if adding another setting for it might add an extra level of confusion?

**Comment by deathau** [comment]
I've added the setting now. I'm also planning on _hiding_ the setting if the folder part can't be used properly (if you're not using the downloads API / Safari)

**Comment by nikiluk** [comment]
@deathau Hi That's great let me check, thank you! The primary purpose why I did it is to reach a higher degree of separation between the files and the other Downloads itself. In my workflow I typically use the sync software to move all the "bookmarked" files and their resources from the Downloads into my Obsidian repo.

**Comment by linfz94** [comment]
i want to know whether it is possible to save the content outside the download folder, i want it to be saved directly in my note folder.

**Comment by barolo** [comment]
> i want to know whether it is possible to save the content outside the download folder, i want it to be saved directly in my note folder.

It is possible with symlinking, that's how I've solved it under macOS

**Pull request merged**
