### PR TITLE
Add direct keyboard shortcut for Download tab as Markdown

### PR DESCRIPTION
**Pull request by quintrino**
Hi, 

I've put in a small PR to add a keyboard shortcut for downloading the current tab to markdown directly. 

Let me know if you me to make any changes.

### CODE REVIEW

**Comment by quintrino** [comment]
Hi @deathau, just wondering if you had any feedback on this?

**Comment by AB1908** [comment]
I'm really hoping this gets merged. I can't imagine having to use a mouse.

**Comment by quintrino** [comment]
@AB1908 to be fair, you don't need a mouse, you can use the *open the popup* keyboard shortcut and then hit enter, but it's two keys instead of just one. :P

**Review by deathau — APPROVED** [review]

**Comment by deathau** [comment]
Sorry it's taken me so long to get around to look into this one

**Pull request merged**
